version: "3"
services:
  app:
    build: .
    depends_on:
      - postgresdb
    environment:
      DATABASE_URL: postgresql://${PG_USER}:${PG_PASSWORD}@localhost:${PG_PORT}/${PG_DB}
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
  postgresdb:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:${PG_PORT}"
    volumes:
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
