version: "3"
services:
  postgresdb:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:${PG_PORT}"
    volumes:
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
